# Generated by Django 5.0.3 on 2024-05-14 12:58

import django.db.models.deletion
import management.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(blank=True, max_length=60, null=True)),
                ('perguntasRespostas', models.JSONField(blank=True, null=True)),
                ('feedback', models.CharField(blank=True, max_length=60, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=25)),
                ('endereco', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=2)),
                ('codigo', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAvaliacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='', verbose_name=management.models.upload_image_colaborador)),
            ],
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=23)),
                ('endereco', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('codigo', models.CharField(max_length=2)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiais', to='management.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='management.empresa')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='management.filial')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('perguntas', models.ManyToManyField(blank=True, null=True, related_name='formularios', to='management.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='Respondido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(blank=True, max_length=255, null=True)),
                ('justificativa', models.CharField(blank=True, max_length=255, null=True)),
                ('avaliacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respondidos', to='management.avaliacao')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondidos', to='management.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='management.area')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='management.empresa')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='management.filial')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='management.area')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='management.empresa')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='management.filial')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='management.setor')),
            ],
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='tipoavaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='management.tipoavaliacao'),
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiposcontratos', to='management.area')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiposcontratos', to='management.cargo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiposcontratos', to='management.empresa')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiposcontratos', to='management.filial')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiposcontratos', to='management.setor')),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data_admissao', models.DateTimeField(blank=True, null=True)),
                ('situacao', models.BooleanField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=15, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=15, null=True)),
                ('data_nascimento', models.DateTimeField(blank=True, null=True)),
                ('data_troca_setor', models.DateTimeField(blank=True, null=True)),
                ('data_troca_cargo', models.DateTimeField(blank=True, null=True)),
                ('data_demissao', models.DateTimeField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=management.models.upload_image_colaborador)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='management.area')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='management.cargo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='management.empresa')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='management.filial')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='management.setor')),
                ('tipocontrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='management.tipocontrato')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='Avaliado',
            fields=[
                ('colaborador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='management.colaborador')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliados', to='management.formulario')),
            ],
            options={
                'verbose_name': 'Avaliado',
                'verbose_name_plural': 'Avaliados',
            },
            bases=('management.colaborador',),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='avaliado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_avaliado', to='management.avaliado'),
        ),
        migrations.CreateModel(
            name='Avaliador',
            fields=[
                ('colaborador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='management.colaborador')),
                ('avaliados', models.ManyToManyField(related_name='avaliadores', to='management.avaliado')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliadores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliador',
                'verbose_name_plural': 'Avaliadores',
            },
            bases=('management.colaborador',),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='avaliador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_avaliador', to='management.avaliador'),
        ),
    ]
