# Generated by Django 5.0.3 on 2024-05-16 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='management.area')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='management.empresa')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='management.filial')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='management.setor')),
            ],
        ),
        migrations.AddField(
            model_name='cargo',
            name='ambiente',
            field=models.ForeignKey(default=56246554, on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='management.ambiente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='ambiente',
            field=models.ForeignKey(default=6456456, on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='management.ambiente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipocontrato',
            name='ambiente',
            field=models.ForeignKey(default=76867868, on_delete=django.db.models.deletion.CASCADE, related_name='tiposcontratos', to='management.ambiente'),
            preserve_default=False,
        ),
    ]
