# Generated by Django 5.0.3 on 2024-05-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliado',
            name='formulario',
        ),
        migrations.AddField(
            model_name='avaliado',
            name='tipoAvaliacao',
            field=models.ManyToManyField(related_name='avaliados', to='management.tipoavaliacao'),
        ),
    ]
