# Generated by Django 5.0.3 on 2024-06-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='feedback',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
