# Generated by Django 5.0.3 on 2024-04-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_filial_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='cnpj',
            field=models.CharField(max_length=23),
        ),
    ]
