# Generated by Django 5.0.3 on 2024-04-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_colaborador_situacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='area',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='filial',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='setor',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='tipocontrato',
        ),
    ]
