# Generated by Django 5.0.3 on 2024-04-22 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_colaborador_area_remove_colaborador_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='management.empresa'),
            preserve_default=False,
        ),
    ]
