# Generated by Django 5.0.3 on 2024-04-16 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_empresa_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filial',
            name='cnpj',
        ),
    ]
