# Generated by Django 5.0.3 on 2024-04-22 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_colaborador_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='management.area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='management.cargo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='filial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='management.filial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='setor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='management.setor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='situacao',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='tipocontrato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='management.tipocontrato'),
            preserve_default=False,
        ),
    ]
