# Generated by Django 5.0.3 on 2024-04-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_remove_filial_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='cnpj',
        ),
    ]
