# Generated by Django 5.0.3 on 2024-04-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_colaborador_area_colaborador_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/colaboradores/'),
        ),
    ]
