# Generated by Django 5.0.3 on 2024-04-22 19:55

import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_colaborador_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=management.models.upload_image_colaborador),
        ),
    ]
