# Generated by Django 5.0.3 on 2024-04-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_remove_empresa_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(default=5345354, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filial',
            name='cnpj',
            field=models.CharField(default=756756757, max_length=23),
            preserve_default=False,
        ),
    ]
