# Generated by Django 5.0.3 on 2024-04-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_empresa_cnpj_filial_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
