# Generated by Django 5.0.3 on 2024-04-23 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_colaborador_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('pergunta', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_avaliacao', models.DateTimeField()),
                ('feedback', models.CharField(blank=True, max_length=500, null=True)),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='management.avaliador')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='management.colaborador')),
                ('tipoavaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='management.tipoavaliacao')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='management.formulario')),
            ],
        ),
    ]
