# Generated by Django 5.0.3 on 2024-04-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_formulario_avaliacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='creat_at',
            new_name='create_at',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='justificativa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='nota',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='resposta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
