# Generated by Django 5.0.3 on 2024-04-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_empresa_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
