# Generated by Django 5.0.3 on 2024-04-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_rename_creat_at_avaliacao_create_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='pergunta',
        ),
        migrations.AddField(
            model_name='formulario',
            name='perguntas',
            field=models.ManyToManyField(related_name='formularios', to='management.pergunta'),
        ),
    ]
