# Generated by Django 5.0.3 on 2024-04-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_pergunta_remove_formulario_pergunta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='periodo',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
