# Generated by Django 5.0.3 on 2024-04-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_avaliacao_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliador',
            name='nome',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
