# Generated by Django 5.0.3 on 2024-04-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_avaliador_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoavaliacao',
            name='nome',
            field=models.CharField(max_length=60),
        ),
    ]
