# Generated by Django 5.0.3 on 2024-05-02 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_tipoavaliacao_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='pergunta',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='management.pergunta'),
            preserve_default=False,
        ),
    ]
