# Generated by Django 5.0.3 on 2024-05-03 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_avaliacao_pergunta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='resposta',
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='management.pergunta'),
        ),
        migrations.CreateModel(
            name='Respondido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(blank=True, max_length=255, null=True)),
                ('justificativa', models.CharField(blank=True, max_length=255, null=True)),
                ('avaliacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respondidos', to='management.avaliacao')),
                ('perguntas', models.ManyToManyField(related_name='respondidos', to='management.pergunta')),
            ],
        ),
    ]
