# Generated by Django 5.0.3 on 2024-05-03 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_remove_avaliacao_resposta_alter_avaliacao_pergunta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='justificativa',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='nota',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='pergunta',
        ),
        migrations.RemoveField(
            model_name='respondido',
            name='perguntas',
        ),
        migrations.AddField(
            model_name='respondido',
            name='pergunta',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='respondidos', to='management.pergunta'),
            preserve_default=False,
        ),
    ]
