# Generated by Django 5.0.3 on 2024-05-06 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_alter_avaliador_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='formulario',
        ),
    ]
