# Generated by Django 5.0.3 on 2024-05-06 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_remove_avaliacao_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='avaliador',
        ),
    ]
