# Generated by Django 5.0.3 on 2024-05-06 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_remove_avaliacao_avaliador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='periodo',
        ),
    ]
