# Generated by Django 5.0.3 on 2024-05-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_remove_avaliacao_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='perguntasRespostas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='periodo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
