# Generated by Django 5.0.3 on 2026-04-15 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diretorio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Diretório',
                'verbose_name_plural': 'Diretórios',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(blank=True, max_length=255, null=True)),
                ('contratado', models.CharField(blank=True, max_length=400, null=True)),
                ('objeto_contrato', models.CharField(blank=True, max_length=400, null=True)),
                ('valor_contrato', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('vigencia', models.CharField(blank=True, max_length=255, null=True)),
                ('setor_interessado', models.CharField(blank=True, max_length=255, null=True)),
                ('responsavel_contratante', models.CharField(blank=True, max_length=255, null=True)),
                ('responsavel_contratado', models.CharField(blank=True, max_length=255, null=True)),
                ('multa_recisao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reajuste', models.CharField(blank=True, max_length=255, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('diretorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='gestaoDocumentos.diretorio')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Alvara',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa_titular', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_alvara', models.CharField(blank=True, max_length=255, null=True)),
                ('setor_interessado', models.CharField(blank=True, max_length=255, null=True)),
                ('responsavel_setor', models.CharField(blank=True, max_length=255, null=True)),
                ('responsavel_alvara', models.CharField(blank=True, max_length=255, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('vigencia', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='alvaras/')),
                ('diretorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alvaras', to='gestaoDocumentos.diretorio')),
            ],
            options={
                'verbose_name': 'Alvará',
                'verbose_name_plural': 'Alvarás',
            },
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('especie', models.BooleanField(default=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('participacao', models.CharField(blank=True, max_length=255, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='acoes/')),
                ('diretorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes', to='gestaoDocumentos.diretorio')),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
            },
        ),
        migrations.CreateModel(
            name='Patrimonial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titular', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_bem', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao_bem', models.CharField(blank=True, max_length=255, null=True)),
                ('localizacao_tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
                ('cep', models.CharField(blank=True, max_length=20, null=True)),
                ('distrito', models.CharField(blank=True, max_length=255, null=True)),
                ('coordenadas', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_cartorio', models.CharField(blank=True, max_length=255, null=True)),
                ('matricula', models.CharField(blank=True, max_length=255, null=True)),
                ('comarca', models.CharField(blank=True, max_length=255, null=True)),
                ('zona', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_contabil', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bemfeitoria', models.CharField(blank=True, max_length=255, null=True)),
                ('area_privativa', models.CharField(blank=True, max_length=255, null=True)),
                ('area_total', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_construcao', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_conservacao', models.CharField(blank=True, max_length=255, null=True)),
                ('padrao_construtivo', models.CharField(blank=True, max_length=255, null=True)),
                ('idade', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='patrimoniais/')),
                ('diretorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimoniais', to='gestaoDocumentos.diretorio')),
            ],
            options={
                'verbose_name': 'Patrimonial',
                'verbose_name_plural': 'Patrimoniais',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('setor_interessado', models.CharField(blank=True, max_length=255, null=True)),
                ('responsavel_setor', models.CharField(blank=True, max_length=255, null=True)),
                ('versao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_versao', models.DateField(blank=True, null=True)),
                ('documento_citado', models.TextField(blank=True, null=True)),
                ('copia_fisica_setores', models.CharField(blank=True, max_length=255, null=True)),
                ('copia_digital_setores', models.CharField(blank=True, max_length=255, null=True)),
                ('periodicidade_auditoria', models.CharField(blank=True, max_length=255, null=True)),
                ('ultima_auditoria', models.DateField(blank=True, null=True)),
                ('periodicidade_reciclagem', models.CharField(blank=True, max_length=255, null=True)),
                ('ultimo_treinamento', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='processos/')),
                ('diretorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='gestaoDocumentos.diretorio')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
            },
        ),
        migrations.CreateModel(
            name='Procuracao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('outorgante', models.CharField(blank=True, max_length=255, null=True)),
                ('outorgado', models.CharField(blank=True, max_length=255, null=True)),
                ('poderes', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('vigencia', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='procuracoes/')),
                ('diretorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procuracoes', to='gestaoDocumentos.diretorio')),
            ],
            options={
                'verbose_name': 'Procuração',
                'verbose_name_plural': 'Procurações',
            },
        ),
    ]
