# Generated by Django 5.0.3 on 2024-12-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('preco_medio_venda', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Médio Venda')),
                ('aliquota', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='Aliquota')),
                ('custo_medio_variavel', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Custo Médio Variável')),
                ('periodo', models.CharField(blank=True, max_length=2, null=True)),
                ('ano', models.CharField(max_length=6)),
                ('quantidade_carregada', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True, verbose_name='Toneladas Carregadas')),
                ('quantidade_produzida', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True, verbose_name='Toneladas Produzidas')),
            ],
            options={
                'verbose_name': ' DRE Linha de Produtos',
                'verbose_name_plural': ' DRE Linhas de Produtos',
            },
        ),
    ]
