# Generated by Django 5.0.3 on 2024-11-13 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0009_colaborador_dominio_id_colaborador_minerion_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaContabil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel_1_conta', models.IntegerField(blank=True, null=True)),
                ('nivel_1_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_2_conta', models.IntegerField(blank=True, null=True)),
                ('nivel_2_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_3_conta', models.IntegerField(blank=True, null=True)),
                ('nivel_3_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_4_conta', models.IntegerField(blank=True, null=True)),
                ('nivel_4_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_5_conta', models.IntegerField(blank=True, null=True)),
                ('nivel_5_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_analitico_conta', models.IntegerField(blank=True, null=True)),
                ('nivel_analitico_nome', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Conta Contabil',
                'verbose_name_plural': 'Contas Contabeis',
            },
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('colaborador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='management.colaborador')),
            ],
            options={
                'verbose_name': 'Gestor',
                'verbose_name_plural': 'Gestores',
            },
            bases=('management.colaborador',),
        ),
        migrations.CreateModel(
            name='RaizSintetica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('raiz_contabil', models.IntegerField()),
                ('descricao', models.CharField(max_length=555)),
                ('natureza', models.IntegerField()),
                ('centro_custo_codigo', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Raiz Sintetica',
                'verbose_name_plural': 'Raizes Sinteticas',
            },
        ),
        migrations.CreateModel(
            name='CentroCustoPai',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orcamentos_ambientes+', to='management.ambiente')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='gestores_areas', to='management.area')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='gestores_empresas+', to='management.empresa')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='gestores_filiais+', to='management.filial')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orcamentos_setores+', to='management.setor')),
            ],
            options={
                'verbose_name': 'CentroCustoPai',
                'verbose_name_plural': 'CentrosCustoPai',
            },
        ),
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('nome', models.CharField(max_length=555)),
                ('cc_pai', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cc_pai', to='orcamento.centrocustopai')),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Centros de Custo Pai+', to='orcamento.gestor')),
            ],
            options={
                'verbose_name': 'Centro de Custo',
                'verbose_name_plural': 'Centros de Custos',
            },
        ),
        migrations.CreateModel(
            name='GrupoItens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('nome_completo', models.CharField(max_length=555)),
                ('nivel_1', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_2', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_3', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_4', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_5', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_6', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_7', models.CharField(blank=True, max_length=255, null=True)),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='gestores_grupos_de_itens', to='orcamento.gestor')),
            ],
            options={
                'verbose_name': 'Grupo de Itens',
                'verbose_name_plural': 'Grupos de Itens',
            },
        ),
        migrations.CreateModel(
            name='RaizAnalitica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('raiz_contabil', models.IntegerField()),
                ('descricao', models.CharField(max_length=555)),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='gestores', to='orcamento.gestor')),
            ],
            options={
                'verbose_name': 'Raiz Analitica',
                'verbose_name_plural': 'Raizes Analiticas',
            },
        ),
        migrations.CreateModel(
            name='OrcamentoBase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.CharField(max_length=255)),
                ('raiz_sintetica_desc', models.CharField(max_length=255)),
                ('raiz_analitica_desc', models.CharField(max_length=555)),
                ('conta_contabil_descricao', models.CharField(blank=True, max_length=555, null=True)),
                ('raiz_contabil_grupo', models.IntegerField()),
                ('raiz_contabil_grupo_desc', models.CharField(blank=True, max_length=555, null=True)),
                ('recorrencia', models.CharField(choices=[('anual', 'Anual'), ('mensal', 'Mensal')], max_length=255)),
                ('mensal_tipo', models.CharField(blank=True, choices=[('especifico', 'Mês Específico'), ('recorrente', 'Recorrente')], max_length=255)),
                ('mes_especifico', models.IntegerField(blank=True)),
                ('meses_recorrentes', models.CharField(blank=True, max_length=255)),
                ('suplementacao', models.BooleanField(null=True)),
                ('base_orcamento', models.CharField(blank=True, max_length=555, null=True)),
                ('id_base', models.IntegerField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor')),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orcamentos_ambientes', to='management.ambiente')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='gestores_areas+', to='management.area')),
                ('centro_custo_nome', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orçamentos_ccs+', to='orcamento.centrocusto')),
                ('centro_de_custo_pai', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orcamentosPai+', to='orcamento.centrocustopai')),
                ('conta_contabil', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orcamentos_contas+', to='orcamento.contacontabil')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='gestores_empresas+', to='management.empresa')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='gestores_filiais+', to='management.filial')),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='gestores_orcamentos+', to='orcamento.gestor')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orcamentos_setores+', to='management.setor')),
                ('raiz_analitica', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orcamentos_raiz_analitica+', to='orcamento.raizanalitica')),
                ('raiz_sintetica', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orcamentos_raiz_sintetica+', to='orcamento.raizsintetica')),
            ],
            options={
                'verbose_name': 'Orcamento Base',
                'verbose_name_plural': 'Orcamentos Base',
            },
        ),
    ]
