# Generated by Django 5.0.3 on 2024-11-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrocusto',
            name='codigo',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='contacontabil',
            name='nivel_1_conta',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='contacontabil',
            name='nivel_2_conta',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='contacontabil',
            name='nivel_3_conta',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='contacontabil',
            name='nivel_4_conta',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='contacontabil',
            name='nivel_5_conta',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='contacontabil',
            name='nivel_analitico_conta',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='orcamentobase',
            name='id_base',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orcamentobase',
            name='raiz_contabil_grupo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='raizanalitica',
            name='raiz_contabil',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='raizsintetica',
            name='centro_custo_codigo',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='raizsintetica',
            name='natureza',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='raizsintetica',
            name='raiz_contabil',
            field=models.CharField(max_length=80),
        ),
    ]
