# Generated by Django 5.0.3 on 2024-11-13 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0002_alter_centrocusto_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoitens',
            name='gestor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='gestores_grupos_de_itens', to='orcamento.gestor'),
        ),
    ]
