# Generated by Django 5.0.3 on 2024-11-13 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0003_alter_grupoitens_gestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoitens',
            name='gestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='gestores_grupos_de_itens', to='orcamento.gestor'),
        ),
    ]
