# Generated by Django 5.0.3 on 2024-11-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0004_alter_grupoitens_gestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raizanalitica',
            name='raiz_contabil',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
