# Generated by Django 5.0.3 on 2025-12-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHoraExtra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('colaborador', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('hora_inicial', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Registro de Hora Extra',
                'verbose_name_plural': 'Registros de Hora Extra',
            },
        ),
    ]
