# Generated by Django 5.0.3 on 2024-07-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacalc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='data_fim',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='data_inicio',
            field=models.DateTimeField(),
        ),
    ]
