# Generated by Django 5.0.3 on 2024-07-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacalc', '0002_alter_periodo_data_fim_alter_periodo_data_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='data_fim',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='data_inicio',
            field=models.DateField(),
        ),
    ]
