# Generated by Django 5.0.3 on 2024-07-05 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacalc', '0003_alter_periodo_data_fim_alter_periodo_data_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodo',
            old_name='data_fim',
            new_name='dataFim',
        ),
        migrations.RenameField(
            model_name='periodo',
            old_name='data_inicio',
            new_name='dataInicio',
        ),
    ]
